baseURL = "https://anubhabdas.com/"
languageCode = "en-us"
title = "Anubhab Das"
theme = "qubt"

[params]
  [params.author]
    name = "Anubhab Das"
    email = "anubhabd06@gmail.com"
    
  description = "Ceramic Engineering Student at GCECT, Kolkata"
  keywords = ["ceramic engineering", "materials science", "GCECT"]
  
  # Social links (optional)
  [params.social]
    email = "anubhabd06@gmail.com"
    phone = "+91-9038831854"

[menu]
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 1
  
  [[menu.main]]
    name = "Research"
    url = "/research/"
    weight = 2
  
  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 3

   [[menu.main]]
    name = "Skills"
    url = "/skills/"
    weight = 4

  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 5

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true